services: 
  app:
    build: ./src/frontend
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend/:/app
      - /app/node_modules'

  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app